# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ exiv ]
  pull_request:
    branches: [ exiv ]

env:
  CI: true

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04,ubuntu-18.04, ubuntu-20.04, macos-latest, macos-11.0]

    steps:
      - uses: actions/checkout@v2

#      - name: apt
#        if: runner.os =='Linux'
##        run: sudo apt-get install  libexiv2-dev

 
      - name: Get exiv2
#        if: steps.cache-opencv.outputs.cache-hit != 'true'
#        if: runner.os !='Linux'       
        uses: actions/checkout@v2
        with:
          repository: Exiv2/exiv2
          path: exiv2
          token: ${{ github.token }}
          ref: ${{secrets.EXIV2_VERSION}}

      # (eigen?), matrix build, checkout CMakeList.txt in .../static
      - name: Build exiv2
#        if: runner.os !='Linux'
#        if: steps.cache-opencv.outputs.cache-hit != 'true'
        run: |
          cd exiv2
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DEXIV2_ENABLE_NLS=OFF -DEXIV2_BUILD_SAMPLES=OFF  -DEXIV2_ENABLE_XMP=OFF .. 
          cmake --build .
          sudo make install
          
      - name: list
        run: |
          ls -altrh /usr/local/lib/
          ls -altrh /usr/lib/

      - name: j3AstroIOexiv
        env:
          CI: true
        run: |
          mkdir -p build
          cd build
          cmake ../ci
          make
          make package
 
      - name: unpack mac
        if: runner.os !='Linux'
        run: tar xzvf build/j3AstroIOexiv-1.0.0-Darwin.tar.gz

      - name: unpack linux
        if: runner.os =='Linux' 
        run: tar xzvf build/j3AstroIOexiv-1.0.0-Linux.tar.gz

      - name: archive results max
        if: runner.os !='Linux' 
        uses: actions/upload-artifact@v1
        with:
          name: j3AstroIOexiv-1.0.0-${{ matrix.os }}
          path: j3AstroIOexiv-1.0.0-Darwin

      - name: archive results linux
        if:  runner.os =='Linux' 
        uses: actions/upload-artifact@v1
        with:
          name: j3AstroIOexiv-1.0.0-${{ matrix.os }}
          path: j3AstroIOexiv-1.0.0-${{ runner.os }}
 