# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ magic ]
  pull_request:
    branches: [ magic ]

env:
  CI: true


jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, macos-11.0]

    steps:
      - uses: actions/checkout@v2

     
      - name: j3AstroIO
        run: |
          mkdir -p build
          cd build
          cp /usr/share/file/magic.mgc ../ci/
          cmake ../ci/
          make
          make package
 
      - name: archive results mac
        if: runner.os !='Linux' 
        uses: actions/upload-artifact@v1
        with:
          name: j3AstroIO-1.0.0-${{ matrix.os }}
          path: build/j3AstroIO-1.0.0-Darwin.tar.gz

      - name: archive results linux
        if:  runner.os =='Linux' 
        uses: actions/upload-artifact@v1
        with:
          name: j3AstroIO-1.0.0-${{ matrix.os }}
          path: build/j3AstroIO-1.0.0-${{ runner.os }}.tar.gz
 
